services:
  postgres:
    image: postgres:16-alpine
    container_name: kanban-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kanban_db
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanban_user -d kanban_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
